module.exports = {
  rules: {
    'array-type': [true, 'array-simple'],
    'arrow-return-shorthand': true,
    'ban-ts-ignore': true,
    'ban-types': [
      true,
      ['Object', 'Use {} instead.'],
      ['String', "Use 'string' instead."],
      ['Number', "Use 'number' instead."],
      ['Boolean', "Use 'boolean' instead."],
    ],
    'binary-expression-operand-order': true,
    'class-name': true,
    'comment-format': [
      true,
      'check-space',
      'check-uppercase',
      { 'ignore-words': ['TODO'] },
    ],
    'comment-type': [true, 'doc', 'singleline'],
    curly: [true, 'ignore-same-line'],
    'cyclomatic-complexity': true,
    'file-name-casing': [
      true,
      {
        '.tsx': 'pascal-case',
        '.style.ts': 'kebab-case',
        '.*': 'camel-case',
      },
    ],
    forin: true,
    'interface-name': [true, 'never-prefix'],
    'interface-over-type-literal': true,
    'label-position': true,
    'max-classes-per-file': [true, 1],
    'member-access': [true, 'no-public'],
    'new-parens': true,
    'newline-per-chained-call': true,
    'no-angle-bracket-type-assertion': true,
    'no-any': true,
    'no-arg': true,
    'no-conditional-assignment': true,
    'no-construct': true,
    'no-debugger': true,
    'no-default-export': true,
    'no-duplicate-variable': [true, 'check-parameters'],
    'no-empty': true,
    'no-inferrable-types': true,
    'no-namespace': [true, 'allow-declarations'],
    'no-reference': true,
    'no-shadowed-variable': true,
    'no-string-throw': true,
    'no-reference-import': true,
    'no-return-await': true,
    'no-unnecessary-callback-wrapper': true,
    'no-unnecessary-class': true,
    'no-unnecessary-initializer': true,
    'no-unsafe-finally': true,
    'no-unused-expression': true,
    'no-var-keyword': true,
    'object-literal-key-quotes': [true, 'consistent-as-needed'],
    'object-literal-shorthand': true,
    'object-literal-sort-keys': true,
    'one-variable-per-declaration': [true, 'ignore-for-loop'],
    'only-arrow-functions': [
      true,
      'allow-declarations',
      'allow-named-functions',
    ],
    'ordered-imports': [true, { 'named-imports-order': 'case-insensitive' }],
    'prefer-conditional-expression': [true, 'check-else-if'],
    'prefer-const': true,
    'prefer-method-signature': true,
    'prefer-object-spread': true,
    'prefer-switch': true,
    'prefer-template': true,
    'prefer-while': true,
    radix: true,
    semicolon: [true, 'always', 'ignore-bound-class-methods'],
    'static-this': true,
    'switch-default': true,
    'trailing-comma': [
      true,
      {
        multiline: {
          objects: 'always',
          arrays: 'always',
          functions: 'never',
          typeLiterals: 'ignore',
        },
        esSpecCompliant: true,
      },
    ],
    'triple-equals': [true, 'allow-null-check'],
    'unnecessary-bind': true,
    'unnecessary-constructor': true,
    'unnecessary-else': true,
    'use-isnan': true,
    'variable-name': [
      true,
      'check-format',
      'ban-keywords',
      'allow-leading-underscore',
      'require-const-for-all-caps',
    ],
  },
};
